**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/creating-reading-and-writing).**

---

In [2]:
import sys

In [3]:
sys.version

'3.7.9 | packaged by conda-forge | (default, Feb 13 2021, 20:03:11) \n[GCC 9.3.0]'

# Introduction

The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

Run the code cell below to load libraries you will need (including code to check your answers).

In [4]:
import pandas as pd
pd.set_option('max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

In [ ]:
#pd.max_rows

# Exercises

## 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [9]:
fruits = pd.DataFrame([[30,21]],columns=['Apples','Banana'])

In [10]:
fruits

   Apples  Banana
0      30      21

In [11]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits = ____

# Check your answer
q1.check()
fruits

Check: When you've updated the starter code, `check()` will tell you whether your code is correct. You need to update the code that creates variable `fruits`

In [ ]:
#q1.hint()
#q1.solution()

In [17]:
fruits=pd.DataFrame([[35,21],[41,34]], columns=['Apples','Bananas'], index=['2017 Sales','2018 Sales'])

In [18]:
fruits

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [19]:
fruits['Apples'][0]

35

In [23]:
fruits['Bananas'][1]

34

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://i.imgur.com/CHPn7ZF.png)

In [24]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = ____

# Check your answer
q2.check()
fruit_sales

Check: When you've updated the starter code, `check()` will tell you whether your code is correct. You need to update the code that creates variable `fruit_sales`

In [25]:
q2.hint()
q2.solution()

Hint: Set the row labels in the DataFrame by using the `index` parameter in `pd.DataFrame`.

Solution:
```python
fruit_sales = pd.DataFrame([[35, 21], [41, 34]], columns=['Apples', 'Bananas'],
                index=['2017 Sales', '2018 Sales'])
```

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [35]:
ingredients=pd.Series(['4 cups','1 cup','2 large','1 can'], index=['Flour','Milk','Eggs','Spam'], name='Dinner')

In [36]:
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [37]:
ingredients = pd.Series

# Check your answer
q3.check()
ingredients

Incorrect: Expected `ingredients` to have type `<class 'pandas.core.series.Series'>` but had type `<class 'type'>`

pandas.core.series.Series

NameError: name 'quantities' is not defined

In [41]:
q3.hint()
q3.solution()

Hint: Note that the Series must be named `"Dinner"`. Use the `name` keyword-arg when creating your series.

Solution:
```python
quantities = ['4 cups', '1 cup', '2 large', '1 can']
items = ['Flour', 'Milk', 'Eggs', 'Spam']
recipe = pd.Series(quantities, index=items, name='Dinner')
```

In [43]:
quantities = ['4 cups', '1 cup', '2 large', '1 can']

In [44]:
items = ['Flour', 'Milk', 'Eggs', 'Spam']

In [46]:
dp=pd.Series(quantities, index=items, name='Dinner')

In [47]:
dp

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [58]:
!ls -l

total 12
drwxr-xr-x 12 root root 4096 Jun  7 04:13 input
drwxr-xr-x  3 root root 4096 Jun  7 04:13 lib
drwxr-xr-x  2 root root 4096 Jun  7 04:13 working

In [56]:
!pwd

/kaggle/input/wine-reviews

In [59]:
%cd ./working

/kaggle/working

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://i.imgur.com/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [63]:
reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv')

# Check your answer
#q4.check()
reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...,...
150928,150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [65]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [ ]:
q4.hint()
q4.solution()

## 5.

Run the cell below to create and display a DataFrame called `animals`:

In [66]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [68]:
animals['Cows'][0]

12

In [69]:
animals['Goats'][0]

22

In [76]:
animals[0:2]

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [77]:
animals.to_csv('animal.csv')

In the cell below, write code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`.

In [78]:
!ls -l

total 8
---------- 1 root root 263 Jun  7 04:13 __notebook_source__.ipynb
-rw-r--r-- 1 root root  38 Jun  7 05:12 animal.csv

In [87]:
pd1=pd.read_csv('./animal.csv', index_col=0)

In [88]:
pd1

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [ ]:
# Your code goes here

# Check your answer
q5.check()

In [ ]:
#q5.hint()
#q5.solution()

# Keep going

Move on to learn about **[indexing, selecting and assigning](https://www.kaggle.com/residentmario/indexing-selecting-assigning)**.

---




*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum/161299) to chat with other Learners.*